package com.rodrigmatrix.weatheryou.presentation.preview

import com.rodrigmatrix.weatheryou.weathericons.R
import com.rodrigmatrix.weatheryou.domain.model.*

val PreviewWeatherList = listOf(
    WeatherLocation(
        name = "Toronto",
        latitude = 0.0,
        longitude = 0.0,
        isCurrentLocation = false,
        currentWeather = 1.0,
        feelsLike = -2.0,
        maxTemperature = 10.0,
        lowestTemperature = 0.0,
        currentWeatherDescription = "Snow",
        weatherIcons = WeatherIcons(
            animatedIcon = 0,
            staticIcon = R.drawable.ic_weather_partly_shower
        ),
        currentTime = "11:00 PM",
        timeZone = "",
        precipitationProbability = 0.0,
        precipitationType = "",
        humidity = 87.0,
        dewPoint = 22.0,
        windSpeed = 0.0,
        windDirection = 0.0,
        uvIndex = 0.0,
        sunrise = "",
        sunset = "",
        visibility = 0.0,
        pressure = 0.0,
    ),
    WeatherLocation(
        name = "Montreal",
        latitude = 0.0,
        longitude = 0.0,
        isCurrentLocation = false,
        currentWeather = -10.0,
        feelsLike = -2.0,
        maxTemperature = 10.0,
        lowestTemperature = 0.0,
        currentWeatherDescription = "Snow",
        weatherIcons = WeatherIcons(
            animatedIcon = 0,
            staticIcon = R.drawable.ic_weather_snow
        ),
        currentTime = "10:00 PM",
        timeZone = "",
        precipitationProbability = 0.0,
        precipitationType = "",
        humidity = 87.0,
        dewPoint = 22.0,
        windSpeed = 0.0,
        windDirection = 0.0,
        uvIndex = 0.0,
        sunrise = "",
        sunset = "",
        visibility = 0.0,
        pressure = 0.0
    ),
    WeatherLocation(
        name = "Montreal",
        latitude = 0.0,
        longitude = 0.0,
        isCurrentLocation = false,
        currentWeather = -10.0,
        feelsLike = -2.0,
        maxTemperature = 10.0,
        lowestTemperature = 0.0,
        currentWeatherDescription = "Snow",
        weatherIcons = WeatherIcons(
            animatedIcon = 0,
            staticIcon = R.drawable.ic_weather_storm
        ),
        currentTime = "10:00 PM",
        timeZone = "",
        precipitationProbability = 0.0,
        precipitationType = "",
        humidity = 87.0,
        dewPoint = 22.0,
        windSpeed = 0.0,
        windDirection = 0.0,
        uvIndex = 0.0,
        sunrise = "",
        sunset = "",
        visibility = 0.0,
        pressure = 0.0
    ),
    WeatherLocation(
        name = "Montreal",
        latitude = 0.0,
        longitude = 0.0,
        isCurrentLocation = false,
        currentWeather = -10.0,
        feelsLike = -2.0,
        maxTemperature = 10.0,
        lowestTemperature = 0.0,
        currentWeatherDescription = "Snow",
        weatherIcons = WeatherIcons(
            animatedIcon = 0,
            staticIcon = R.drawable.ic_weather_rainynight
        ),
        currentTime = "10:00 PM",
        timeZone = "",
        precipitationProbability = 0.0,
        precipitationType = "",
        humidity = 87.0,
        dewPoint = 22.0,
        windSpeed = 0.0,
        windDirection = 0.0,
        uvIndex = 0.0,
        sunrise = "",
        sunset = "",
        visibility = 0.0,
        pressure = 0.0
    ),
    WeatherLocation(
        name = "Montreal",
        latitude = 0.0,
        longitude = 0.0,
        isCurrentLocation = false,
        currentWeather = -10.0,
        feelsLike = -2.0,
        maxTemperature = 10.0,
        lowestTemperature = 0.0,
        currentWeatherDescription = "Snow",
        weatherIcons = WeatherIcons(
            animatedIcon = 0,
            staticIcon = R.drawable.ic_weather_partly_shower
        ),
        currentTime = "10:00 PM",
        timeZone = "",
        precipitationProbability = 0.0,
        precipitationType = "",
        humidity = 87.0,
        dewPoint = 22.0,
        windSpeed = 0.0,
        windDirection = 0.0,
        uvIndex = 0.0,
        sunrise = "",
        sunset = "",
        visibility = 0.0,
        pressure = 0.0
    ),
    WeatherLocation(
        name = "Montreal",
        latitude = 0.0,
        longitude = 0.0,
        isCurrentLocation = false,
        currentWeather = -10.0,
        feelsLike = -2.0,
        maxTemperature = 10.0,
        lowestTemperature = 0.0,
        currentWeatherDescription = "Snow",
        weatherIcons = WeatherIcons(
            animatedIcon = 0,
            staticIcon = R.drawable.ic_weather_night
        ),
        currentTime = "10:00 PM",
        timeZone = "",
        precipitationProbability = 0.0,
        precipitationType = "",
        humidity = 87.0,
        dewPoint = 22.0,
        windSpeed = 0.0,
        windDirection = 0.0,
        uvIndex = 0.0,
        sunrise = "",
        sunset = "",
        visibility = 0.0,
        pressure = 0.0
    ),
    WeatherLocation(
        name = "Montreal",
        latitude = 0.0,
        longitude = 0.0,
        isCurrentLocation = false,
        currentWeather = -10.0,
        feelsLike = -2.0,
        maxTemperature = 10.0,
        lowestTemperature = 0.0,
        currentWeatherDescription = "Snow",
        weatherIcons = WeatherIcons(
            animatedIcon = 0,
            staticIcon = R.drawable.ic_weather_stormshowersday
        ),
        currentTime = "10:00 PM",
        timeZone = "",
        precipitationProbability = 0.0,
        precipitationType = "",
        humidity = 87.0,
        dewPoint = 22.0,
        windSpeed = 0.0,
        windDirection = 0.0,
        uvIndex = 0.0,
        sunrise = "",
        sunset = "",
        visibility = 0.0,
        pressure = 0.0
    ),
    WeatherLocation(
        name = "Montreal",
        latitude = 0.0,
        longitude = 0.0,
        isCurrentLocation = false,
        currentWeather = -10.0,
        feelsLike = -2.0,
        maxTemperature = 10.0,
        lowestTemperature = 0.0,
        currentWeatherDescription = "Snow",
        weatherIcons = WeatherIcons(
            animatedIcon = 0,
            staticIcon = R.drawable.ic_weather_snow_sunny
        ),
        currentTime = "10:00 PM",
        timeZone = "",
        precipitationProbability = 0.0,
        precipitationType = "",
        humidity = 87.0,
        dewPoint = 22.0,
        windSpeed = 0.0,
        windDirection = 0.0,
        uvIndex = 0.0,
        sunrise = "",
        sunset = "",
        visibility = 0.0,
        pressure = 0.0
    ),
    WeatherLocation(
        name = "Montreal",
        latitude = 0.0,
        longitude = 0.0,
        isCurrentLocation = false,
        currentWeather = -10.0,
        feelsLike = -2.0,
        maxTemperature = 10.0,
        lowestTemperature = 0.0,
        currentWeatherDescription = "Snow",
        weatherIcons = WeatherIcons(
            animatedIcon = 0,
            staticIcon = R.drawable.ic_weather_snow
        ),
        currentTime = "10:00 PM",
        timeZone = "",
        precipitationProbability = 0.0,
        precipitationType = "",
        humidity = 87.0,
        dewPoint = 22.0,
        windSpeed = 0.0,
        windDirection = 0.0,
        uvIndex = 0.0,
        sunrise = "",
        sunset = "",
        visibility = 0.0,
        pressure = 0.0
    )
)