version: 2.1

orbs:
  android: circleci/android@3.0.0  # Use the latest version of the Android orb

jobs:
  build-and-upload-to-play:
    executor:
      name: android/android
      resource-class: medium  # Adjust resource class as needed
    steps:
      - checkout
      - android/restore-gradle-cache  # Restore Gradle cache

      # Load .env file and export variables
      - run:
          name: Load .env file
          command: |
            if [ -f .env ]; then
              export $(grep -v '^#' .env | xargs)
            fi

      # Install gcloud CLI
      - run:
          name: Install gcloud CLI
          command: |
            echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
            sudo apt-get install apt-transport-https ca-certificates gnupg -y
            curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
            sudo apt-get update && sudo apt-get install google-cloud-sdk -y

      # Authenticate with Google Cloud using the service account key
      - run:
          name: Authenticate with Google Cloud
          command: |
            echo $GCLOUD_SERVICE_ACCOUNT_KEY | base64 --decode > /tmp/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=/tmp/gcloud-service-key.json

      # Build .aab files
      - run:
          name: Build .aab files
          command: ./gradlew :app:bundleRelease :tv:bundleRelease

      # Upload .aab files to Google Play Console
      - run:
          name: Upload .aab files to Google Play Console
          command: |
            gcloud config set project $GOOGLE_PLAY_KEY
            gcloud firebase app distribution apps list --project=$GOOGLE_PLAY_KEY
            gcloud firebase app distribution releases upload \
              --app <your-app-id> \
              --release-notes-file <path-to-release-notes> \
              app/build/outputs/bundle/release/app-release.aab

      - android/save-gradle-cache  # Save Gradle cache

  build-and-upload-to-artifacts:
    executor:
      name: android/android
      resource-class: medium  # Adjust resource class as needed
    steps:
      - checkout
      - android/restore-gradle-cache  # Restore Gradle cache

      # Load .env file and export variables
      - run:
          name: Load .env file
          command: |
            if [ -f .env ]; then
              export $(grep -v '^#' .env | xargs)
            fi

      # Build .apk files
      - run:
          name: Build .apk files
          command: ./gradlew :app:assembleRelease :tv:assembleRelease

      # Upload .apk files to CircleCI artifacts
      - store_artifacts:
          path: app/build/outputs/apk/release/app-release.apk
          destination: app-release.apk
      - store_artifacts:
          path: tv/build/outputs/apk/release/tv-release.apk
          destination: tv-release.apk

      - android/save-gradle-cache  # Save Gradle cache

workflows:
  version: 2
  upload-to-play:
    jobs:
      - build-and-upload-to-play:
          filters:
            branches:
              only: 
                - main
                - dev

  upload-to-artifacts:
    jobs:
      - build-and-upload-to-artifacts:
          filters:
            branches:
              ignore: 
                - main
                - dev