package com.rodrigmatrix.weatheryou.presentation.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF006399)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFcbe5ff)
val md_theme_light_onPrimaryContainer = Color(0xFF001d32)
val md_theme_light_secondary = Color(0xFF00677c)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFacecff)
val md_theme_light_onSecondaryContainer = Color(0xFF001f27)
val md_theme_light_tertiary = Color(0xFF00696d)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFF6ef6fc)
val md_theme_light_onTertiaryContainer = Color(0xFF002022)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfcfcff)
val md_theme_light_onBackground = Color(0xFF1a1c1e)
val md_theme_light_surface = Color(0xFFfcfcff)
val md_theme_light_onSurface = Color(0xFF1a1c1e)
val md_theme_light_surfaceVariant = Color(0xFFdee3eb)
val md_theme_light_onSurfaceVariant = Color(0xFF41474d)
val md_theme_light_outline = Color(0xFF72787f)
val md_theme_light_inverseOnSurface = Color(0xFFf0f0f3)
val md_theme_light_inverseSurface = Color(0xFF2f3032)

val md_theme_dark_primary = Color(0xFF90ccff)
val md_theme_dark_onPrimary = Color(0xFF003352)
val md_theme_dark_primaryContainer = Color(0xFF004b75)
val md_theme_dark_onPrimaryContainer = Color(0xFFcbe5ff)
val md_theme_dark_secondary = Color(0xFF58d6f7)
val md_theme_dark_onSecondary = Color(0xFF003642)
val md_theme_dark_secondaryContainer = Color(0xFF005566)
val md_theme_dark_onSecondaryContainer = Color(0xFFacecff)
val md_theme_dark_tertiary = Color(0xFF4cd9df)
val md_theme_dark_onTertiary = Color(0xFF00373a)
val md_theme_dark_tertiaryContainer = Color(0xFF004f52)
val md_theme_dark_onTertiaryContainer = Color(0xFF6ef6fc)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF1a1c1e)
val md_theme_dark_onBackground = Color(0xFFe2e2e5)
val md_theme_dark_surface = Color(0xFF1a1c1e)
val md_theme_dark_onSurface = Color(0xFFe2e2e5)
val md_theme_dark_surfaceVariant = Color(0xFF41474d)
val md_theme_dark_onSurfaceVariant = Color(0xFFc2c7ce)
val md_theme_dark_outline = Color(0xFF8c9198)
val md_theme_dark_inverseOnSurface = Color(0xFF1a1c1e)
val md_theme_dark_inverseSurface = Color(0xFFe2e2e5)