package com.rodrigmatrix.weatheryou.tv.presentation.theme

import androidx.compose.ui.graphics.Color

val md_theme_dark_primary = Color(0xFF9AD768)
val md_theme_dark_onPrimary = Color(0xFF193800)
val md_theme_dark_primaryContainer = Color(0xFF275000)
val md_theme_dark_onPrimaryContainer = Color(0xFFB5F481)
val md_theme_dark_secondary = Color(0xFFBECBAE)
val md_theme_dark_onSecondary = Color(0xFF29341F)
val md_theme_dark_secondaryContainer = Color(0xFF3F4A34)
val md_theme_dark_onSecondaryContainer = Color(0xFFDAE7C9)
val md_theme_dark_tertiary = Color(0xFFA0CFCD)
val md_theme_dark_onTertiary = Color(0xFF003736)
val md_theme_dark_tertiaryContainer = Color(0xFF1E4E4D)
val md_theme_dark_onTertiaryContainer = Color(0xFFBBECEA)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1A1C18)
val md_theme_dark_onBackground = Color(0xFFE3E3DC)
val md_theme_dark_surface = Color(0xFF1A1C18)
val md_theme_dark_onSurface = Color(0xFFE3E3DC)
val md_theme_dark_surfaceVariant = Color(0xFF44483E)
val md_theme_dark_onSurfaceVariant = Color(0xFFC4C8BA)
val md_theme_dark_inverseOnSurface = Color(0xFF1A1C18)
val md_theme_dark_inverseSurface = Color(0xFFE3E3DC)
